version: "3.4"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: devops
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
    volumes:
      - mysqldb:/var/lib/mysql:rw

  springapp:
    image: mohamednakbi/kaddem:2.4
    container_name: springapp
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/devops?useUnicode=yes&useJDBCCompliantTimezoneShift=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    volumes:
      - .m2:/root/.m2
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb

volumes:
  mysqldb:
  
  
