version: "3.9"
services:
  spring:
    depends_on: [mysql]
    image: mysql:latest
    container_name: spring

    restart: unless-stopped
    ports:
      - "8089:8089"


    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5Dialect
    networks:
      - my_network

  mysql:
    image: mysql:latest
    restart: unless-stopped
    container_name: spring
    environment:
      MYSQL_DATABASE: devops
      MYSQL_ROOT_PASSWORD: 
      MYSQL_PASSWORD:
    ports:
      - "3037:3306"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
