version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: devops
    ports:
      - "3308:3306"
    volumes:
      - db:/var/lib/mysql

  springapp:
    image: mohamednakbi/kaddem:2.4
    container_name: springapp
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/devops?useUnicode=yes&useJDBCCompliantTimezoneShift=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    depends_on:
      - db

volumes:
  db:
