version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "devops"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db:/var/lib/mysql

  spring_app:
    container_name: devops
    image: hamzasbaii/devops-project-2.1
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/devops?createDatabaseIfNotExist=true"
      SPRING_DATASOURCE_USERNAME: "root"
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect"
      "spring.jpa.hibernate.ddl-auto" : "update"
    volumes:
      - .m2:/root/.m2
    ports:
      - 8082:8082
    depends_on:
      - mysqldb

volumes:
  db:
