version: "3.8"

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devops
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - NOTwork

  backend:
    image: backend
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - 8083:8083
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url=jdbc:mysql://mysqldb:3306/devops?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
    volumes:
      - ./m2:/root/.m2
    networks:
      - NOTwork

  frontend:
    image: frontend
    build: ./DevOps_Project_Front
    restart: on-failure
    ports:
      - 8181:80
    networks:
      - NOTwork

networks:
  NOTwork:
    driver: bridge

volumes:
  db:
